### ISSUE TITLE
node-sass failure on npm install

### ISSUE THREAD

**Issue by WesleyWaffles** [joeeames/PSAngularUnitTestingCourse#29]
Fresh clone of the repo on my machine produces a failure on npm install. The error message is one I would expect if the node-sass repo was blocked by a proxy (I've encountered this at work), but I'm on a personal machine and network for this so I'm confused as to why it's happening. It appears to be [this issue ](https://github.com/sass/node-sass/issues/2662) and just the version of some package or another is pointing to an unavailable node-sass version. Regardless, the details and error are below. I do not have this problem when creating new Angular app, so I wonder if version bumping this repo would solve it, but that can be challenging for sure. I'm going to try to continue the course using a WSL 2 Ubuntu instance and see how that goes.

Windows Version:  10.0.19041 Build 19041
Node Version: 12.18.2
NPM Version: 6.14.5
Angular CLI Vesion: 10.0.1

Error Output:

 npm install

> node-sass@4.10.0 install C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.10.0 postinstall C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Wesle\\repos\\PSAngularUnitTestingCourse\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.18.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Wesle\\repos\\PSAngularUnitTestingCourse\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Wesle\repos\PSAngularUnitTestingCourse\node_modules\node-sass
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 (node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 1178 packages in 7.006s
found 2347 vulnerabilities (1718 low, 16 moderate, 611 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by WesleyWaffles** [comment]
Can confirm this failed in my Ubuntu environment the exact same way. :/

**Comment by baraksu** [comment]
Hi
The project is not updated with the latest version of the packages. 
I fixed it with the following steps:
1. Update the packages to the latest:
1.1 npm install -g npm-check-updates
1.2 ncu -u
2 Delete the local node_modules folder
3 Install the npm
3.1 npm install
4 update the files polyfills.ts and test.ts with files from a new project.
4.1  To create a new project run:ng new myNewProject
